# nfs pvc for files
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jmx-nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
